/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basedatos;

/**
 *
 * @author David
 */
public class MenuBases extends javax.swing.JFrame {

    /**
     * Creates new form MenuBases
     */
    public MenuBases(Server s, BaseDatos bd) {
        baseDatos = bd;
        server = s;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bcrear = new javax.swing.JButton();
        Beliminar = new javax.swing.JButton();
        BInReg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        B_cancelar = new javax.swing.JButton();
        B_Cnombre = new javax.swing.JButton();
        b_ElReg = new javax.swing.JButton();
        b_SelReg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Bcrear.setText("Crear tabla");
        Bcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcrearActionPerformed(evt);
            }
        });

        Beliminar.setText("Eliminar tabla");
        Beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliminarActionPerformed(evt);
            }
        });

        BInReg.setText("Insertar Registro");
        BInReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInRegActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Menu de Base de Datos");

        B_cancelar.setText("Cancelar");
        B_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cancelarActionPerformed(evt);
            }
        });

        B_Cnombre.setText("Cambiar Nombre");
        B_Cnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CnombreActionPerformed(evt);
            }
        });

        b_ElReg.setText("Eliminar Registros");
        b_ElReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ElRegActionPerformed(evt);
            }
        });

        b_SelReg.setText("Seleccionar Registros");
        b_SelReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_SelRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BInReg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(b_SelReg))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Beliminar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Bcrear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B_Cnombre)
                                    .addComponent(b_ElReg)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(B_cancelar)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bcrear)
                    .addComponent(B_Cnombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Beliminar)
                    .addComponent(b_ElReg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_SelReg)
                    .addComponent(BInReg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(B_cancelar)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcrearActionPerformed
        // TODO add your handling code here:
        CrearTabla crearTabla = new CrearTabla(server, baseDatos);
        crearTabla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BcrearActionPerformed

    private void BInRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInRegActionPerformed
        // TODO add your handling code here:
        InsertarRegistro insertarRegistro = new InsertarRegistro(server,baseDatos);
        insertarRegistro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BInRegActionPerformed

    private void B_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cancelarActionPerformed
        // TODO add your handling code here:
        new SeleccionBD().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_B_cancelarActionPerformed

    private void BeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminarActionPerformed
        // TODO add your handling code here:
        new EliminarTabla(server, baseDatos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BeliminarActionPerformed

    private void B_CnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CnombreActionPerformed
        // TODO add your handling code here:
        new ChangeName(server, baseDatos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_B_CnombreActionPerformed

    private void b_ElRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ElRegActionPerformed
        // TODO add your handling code here:
        new EliminarRegistros(server, baseDatos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_ElRegActionPerformed

    private void b_SelRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_SelRegActionPerformed
        // TODO add your handling code here:
        new SeleccionarDatos(server, baseDatos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_SelRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuBases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuBases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuBases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuBases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuBases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BInReg;
    private javax.swing.JButton B_Cnombre;
    private javax.swing.JButton B_cancelar;
    private javax.swing.JButton Bcrear;
    private javax.swing.JButton Beliminar;
    private javax.swing.JButton b_ElReg;
    private javax.swing.JButton b_SelReg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
Server server;
BaseDatos baseDatos;
}
